do_train: true
do_eval: true
data_dir: ~/git_repos/DeepIMV/data/ICL104-MAR2024
train_data_paths: [metab_train.csv, lip_neg_train.csv, pro_train.csv]
test_data_paths: [metab_test.csv, lip_neg_test.csv, pro_test.csv]
fdata_paths: [metab_fdata_mlready.csv, lip_fdata_mlready.csv, pro_fdata_mlready.csv]
hidden_sizes: [[128, 64], [128, 64], [128, 64]]
activation_fn:
  _target_: hydra.utils.get_method
  path: torch.nn.functional.tanh
combine_fn: 'mean'
learning_rate: 0.0001
dropout: 0.2
hidden_dim: 128
alpha: null
gamma: 2
marginal_loss: true
marginal_coefs: null
marginal_weight: null
shapley: true
igrads: true
output_dir: data/output
best_model_path: data/best_model.pt
final_model_path: data/final_model.pt
patience: 10
validation_frequency: 100
max_iter: 5000
eval_clustering: true
eval_prediction: true
top_n: [0.1, 0.25, 0.5, 0.75, 1.0]
experiment_name: default
    