# @package _global_
# @package hydra.sweeper
_target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
max_batch_size: null
params:
  hidden_sizes: "
    [[92, 64], [152, 64], [1105, 64]],\
    [[76, 32], [136, 32], [1089, 32]],\
    [[68, 16], [128, 16], [1081, 16]],\
    [[92, 64], [184, 128], [1645, 1144]],\
    [[76, 32], [152, 64], [1359, 572]],\
    [[68, 16], [136, 32], [1216, 286]]"
  combine_fn: "concat"
  hidden_dim: 64, 32
  data_dir: /Users/clab683/git_repos/DeepIMV/data/ICL104-binary
  experiment_name: icl-binary
  