# @package _global_
# @package hydra.sweeper
_target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
max_batch_size: null
params:
  hidden_sizes: "[[42, 8], [130, 8], [1265, 8]], [[46, 16], [134, 16], [1269, 16]], [[54, 32], [142, 32], [1277, 32]],[[70, 64], [158, 64], [1293, 64]], [[128], [128], [128]]"
  combine_fn: "mean"
  hidden_dim: 64, 32, 16