# @package _global_
# @package hydra.sweeper
_target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
max_batch_size: null
params:
  layer_x_noise: "{layer_sizes: [[128, 128], [256, 256]], n_noise:100}, {layer_sizes:[[128, 128], [256, 256]], n_noise:500}, {layer_sizes:[[128, 128], [256, 256]], n_noise:1000}, {layer_sizes:[[128, 128], [256, 256]], n_noise:2500}, {layer_sizes:[[128, 128], [256, 256]], n_noise:4000}, {layer_sizes:[[148, 148], [256, 256]], n_noise:100}, {layer_sizes:[[192, 192], [256, 256]], n_noise:500}, {layer_sizes:[[223, 223], [256, 256]], n_noise:1000}, {layer_sizes:[[256, 256], [256, 256]], n_noise:2500}, {layer_sizes:[[309, 309], [256, 256]], n_noise:4000}"
  datasets: ['metab', 'lip']
